module.exports = {
  SUCCESS_MSG: 'Successfully Data Fetch',
  SUCCESS_INSERT: 'Record Sucessfully Inserted.',
  SUCCESS_UPDATE: 'Record Sucessfully Updated.',
  SUCCESS_DELETE: 'Record Sucessfully Deleted.',
  SUCCESS_ACTIVE: 'Record Sucessfully Activated.',
  SUCCESS_DEACTIVE: 'Record Sucessfully Deactivated.',
  SUCCESS_REVIEW: 'Thank you for review',
  SUCCESS_RESETPASS: 'Password Successfully Updatesd',
  TREND: 'Product display on trend.',
  NOTTREND: 'Product not display on trend.',
  FAIL_GET: 'No Data Found.',
  PRODUCT_NOT_FOUND: 'No such product exists!',
  CART_QNT_ERR: 'Please Check product quantity',
  ORDER_QNT_ERR: 'Please Check your cart',
  ORDER_CANCEL: 'Cancel order successfully',
  AUTHENTICATION_ERR: 'Authentication error',
  USER_EMAIL_EXISTS: 'Email has been already registered.',
  USER_NOT_EXIST: "User not found",
  INVALID_OTP: "Invalid OTP",
  MAIL_SEND: "Email Sucessfully Send",
  WISHLIST_INSERT: 'Product Added to Wishlist.',
  WISHLIST_REMOVE: 'Product Removed from Wishlist.',
  SUCCESS_SUBSCRIBE: 'You have been sucessfully subscribe to our newsletters!',
  COUPON_EXPIRED: 'Coupon code expired.',
  SUCCESS_VERIFY: 'User verification successfull',
  NOT_VERIFIED: 'User not verified',
  FAIL_GET_COUPONCODE: 'No Coupon Code Found.',
  COUPONCODE_USED: 'Coupon Code already used.'
};
